/* Dev log — newest first */

import { DevLogEntry } from '../../types';

export const DEV_LOG_ENTRIES: DevLogEntry[] = [
  {
    id: 'contact-page',
    date: '2026-03-10',
    title: 'Contact Page Without a Backend (Yet)...',
    summary: 'Built the whole form, validation, success state, but it doesn\'t actually send anywhere.',
    category: 'decision',
    tags: ['React', 'Forms', 'Validation'],
    body: [
      'The contact page has a fully working form with field validation, error messages, focus states, etc. Hit submit and you get a nice green checkmark. Currently, there\'s no backend to receive it yet. The Lambda + DynamoDB setup is on the roadmap but I wanted the UI to look right first.',
      'Validation is basic but does the job — checks for empty required fields and runs a regex on the email. The plan is to wire up a POST to /api/contact once the API Gateway is in place. For now the handleSubmit just flips a boolean.',
      'Stole the two-column layout idea from the CV page because it worked well there. Form on the left, sidebar on the right with an availability status and social links. Keeps things consistent across the site.',
    ],
    lessonLearned: 'Get the UI right first. It\'s easier to plug in a backend to a finished form than to redesign the frontend around API constraints.',
  },
  {
    id: 'engineering-adrs',
    date: '2026-03-09',
    title: 'Writing ADRs: Explaining "Why" is Harder Than Writing Code',
    summary: 'A time-consuming task, explaining the reasoning behind the design (front and backend)',
    category: 'milestone',
    tags: ['ADR', 'Architecture', 'Documentation'],
    body: [
      'ADRs (Architecture Decision Records) are short docs that explain a technical choice. Context, decision, trade-offs. Simple format, surprisingly hard to write well. I spent more time on these five records than on some of the actual components.',
      'The format comes from Michael Nygard\'s blog post (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) — it\'s been an industry standard for years. Each one forces you to think about what you rejected and why, which is honestly the useful bit.',
      'Made them expandable cards on the engineering page. Click to see the full context. Each one has a green "positive" panel and an amber "trade-offs" panel side by side.',
    ],
    lessonLearned: 'Writing down WHY you chose something is more valuable than documenting what was chosen. The "what" is already in GitHub',
  },
  {
    id: 'system-diagram-no-library',
    date: '2026-03-09',
    title: 'Built the Architecture Diagram With Just Divs',
    summary: 'Considered Mermaid, D3, even draw.io screenshots. Ended up with hover-able coloured boxes.',
    category: 'learning',
    tags: ['React', 'UI', 'Components'],
    body: [
      'I went back and forth on how to show the system architecture. Mermaid.js can generate diagrams from text (https://mermaid.js.org/) but the output looks generic and you can\'t style it easily. D3 is overkill for four boxes stacked on top of each other. Screenshots of diagrams look awful with dark backgrounds and difficult to make it look natural',
      'So I just made it with divs. Each architecture layer is a row that expands on hover to show its components. Wrapped the whole thing in a fake terminal window with the red/yellow/green dots because I like it.',
      'Total implementation: one useState for the active layer, some conditional borders and backgrounds, a max-height transition for the expand. About 80 lines of JSX. Would\'ve been 200+ with a diagramming library and half the control.',
    ],
    lessonLearned: 'Reach for a library when the problem is complex. Reach for a div when the problem is "I need four expandable rows."',
  },
  {
    id: 'devlog-meta',
    date: '2026-03-08',
    title: 'A Dev Log That Logs Its Own Development',
    summary: 'I\'m writing about building the page you\'re reading this on.',
    category: 'learning',
    tags: ['Meta', 'Content', 'TypeScript'],
    body: [
      'This is a bit recursive, the dev log page documents building the dev log page. But that\'s the whole point of this site. Everything is self-referential. The commits page shows the commits that built the commits page. The engineering section documents the engineering behind the engineering section. It\'s the portfolio equivalent of a mirror facing a mirror.',
      'Entries are stored as a TypeScript array in a single file rather than individual MDX files. Could\'ve gone the MDX route (https://mdxjs.com/) but that adds a build plugin, a content processing step, and complexity I don\'t need for ~15 entries. If this grows to 50+ posts I\'ll migrate.',
      'The category filter was a quick win. Five buttons, one useState, one .filter() call. Engineers click "Problems" first (they always do). Recruiters scan "Milestones."',
    ],
    lessonLearned: 'Pick the simplest solution that works today. Migrate when the pain becomes real',
  },
  {
    id: 'github-api',
    date: '2026-03-07',
    title: 'GitHub API: 60 Requests Per Hour is Not a Lot',
    summary: 'Vite\'s hot reload counts as a new request every time. Hit the rate limit within 20 minutes of development.',
    category: 'problem',
    tags: ['GitHub API', 'Rate Limiting', 'React'],
    body: [
      'The commits page fetches live data from GitHub\'s REST API (https://docs.github.com/en/rest). Public repos don\'t need authentication, which is great. But unauthenticated requests are capped at 60 per hour, which is a nightmare when your dev server refetches on every file save.',
      'Burned through the limit within 20 minutes. "API rate limit exceeded" was the issue.',
      'Fixed it by adding error handling to explain that users may have to wait for a new refresh. By the time this is fully hosted - for less than £2/month ;) - this is unlikely to ever occur.',
    ],
    lessonLearned: 'Read the documentation first!',
  },
  {
    id: 'conventional-commits',
    date: '2026-03-06',
    title: 'Conventional Commits: A Habit That Pays for Itself',
    summary: 'Started using feat: and fix: prefixes. Now the commits page auto-categorises everything. Past me is helping present me.',
    category: 'decision',
    tags: ['Git', 'Conventional Commits'],
    body: [
      'Adopted the conventional commits spec (https://www.conventionalcommits.org/) from day one. Every commit starts with a type prefix: feat:, fix:, style:, docs:, refactor:. Felt overengineered at first but it paid off immediately when I built the commits page.',
      'The commit type parser is simple, a chain of startsWith() checks that returns a colour and icon. No regex or parsing library. The function is about 12 lines long. The commits page uses it to colour-code every entry automatically.',
      'The real win is the git log itself. Run "git log --oneline" on this repo and you can scan the entire project history in seconds. Try doing that with commits called "updates" and "fixed thing" and "wip."',
    ],
    lessonLearned: 'Naming commits is easy if you just follow a convention. Pick one and stick to it.',
  },
  {
    id: 'print-css',
    date: '2026-03-05',
    title: 'Printing the CV: !important rule added to every single print rule',
    summary: 'Inline React styles have ridiculous specificity. @media print didn\'t work unless !important was used on every print rule.',
    category: 'learning',
    tags: ['CSS', 'Print', 'React'],
    body: [
      'I assume recruiters still print CVs, even to a PDF. So the CV page needs to look decent on paper. Every style on the page is an inline React style object, which means it has higher specificity than any stylesheet rule',
      'The "correct" fix would be to move all styles to CSS modules or styled-components so the print stylesheet can override them cleanly. But that\'s a massive refactor for one feature. So instead took the lazy man\'s route of using !important on every print rule. It works. It\'s ugly in the code but the printed CV looks great.',
      'Print styles hide the nav, buttons, decorative grids, and the overlay. Switch to white background, dark text. Remove the sticky sidebar so everything flows top-to-bottom. The browser\'s "Save as PDF" option works perfectly too — tested in Chrome and Edge.',
    ],
    lessonLearned: 'Sometimes the "wrong" solution is the right one. !important exists for a reason and @media print was that reason.',
  },
  {
    id: 'cv-layout',
    date: '2026-03-04',
    title: 'CV Layout: Built for scanning, not reading',
    summary: 'Designed the CV page around how recruiters actually read, which is more scanning than reading',
    category: 'decision',
    tags: ['UX', 'Layout', 'CSS Grid'],
    body: [
      'It\'s well known recruiter\'s spend next to no time reading an individual CV. Name, title, location, and current role all need to be visible without any scrolling at all.',
      'Two-column CSS grid: experience timeline on the left (biggest column, where eyes go first), skills sidebar on the right with position: sticky so it follows you down the page. Means you can read through my five roles and always see the skill bars in your peripheral vision.',
      'Each role gets a coloured dot on the timeline. Current role (Cegal) gets a glowing dot with a box-shadow to draw the eye. Tags at the bottom of each role are there for ATS keyword scanners and technical recruiters who ctrl+F for "Docker" or "PL/SQL."',
    ],
    lessonLearned: 'Don\'t design for how people should read your CV. Design for how they actually do — which is a 3-second glance at the top-left corner.',
  },
  {
    id: 'crlf',
    date: '2026-03-03',
    title: '"LF will be replaced by CRLF"',
    summary: 'Windows and Git have different opinions about line endings.',
    category: 'problem',
    tags: ['Windows', 'Git', 'Line Endings'],
    body: [
      'Not exactly an issue, but an observation. As I am using a Windows machine to develop this, every git add throws warnings. Every single file - "LF will be replaced by CRLF the next time Git touches it." Windows uses \\r\\n for line breaks, everyone else uses \\n. Git is politely telling me my OS is the problem (which is true, Linux is superior in this regard).',
      'One command removes this warning: git config --global core.autocrlf true (https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration). Git now converts to LF on commit and back to CRLF locally.',
    ],
    lessonLearned: 'Run git config --global core.autocrlf true on day one of any Windows dev setup to avoid warnings',
  },
  {
    id: 'path-aliases',
    date: '2026-03-02',
    title: 'Smarter Path Aliases',
    summary: 'Wanted clean imports. Got red squiggles in VS Code for 30 minutes because I only configured Vite and forgot TypeScript.',
    category: 'learning',
    tags: ['Vite', 'TypeScript', 'VS Code'],
    body: [
      'Relative imports like ../../../features/cv/pages/CVPage are ugly and break when you move files. Path aliases like @features/cv/pages/CVPage are clean and refactor-proof. Setting them up should be simple. It is not.',
      'Vite needs resolve.alias in vite.config.ts (https://vitejs.dev/config/shared-options#resolve-alias). TypeScript needs paths in tsconfig.json (https://www.typescriptlang.org/tsconfig/#paths). Configure only one and you get an issue. The build works but VS Code shows errors, OR VS Code is happy but the build breaks.',
      'Spent 30 minutes staring at red squiggles before realising I\'d only set up the Vite side. Added the matching tsconfig paths, restarted the TS server (Ctrl+Shift+P → "TypeScript: Restart TS Server"), squiggles gone. Would\'ve been 2 minutes if I\'d read the Vite docs properly the first time.',
    ],
    lessonLearned: 'READ THE DOCUMENTATION!',
  },
  {
    id: 'scaffold',
    date: '2026-03-01',
    title: 'Day One: Folder Structure Before Features',
    summary: 'Spent the first day setting up folders and config instead of writing any actual UI. Best decision of the project.',
    category: 'milestone',
    tags: ['React', 'Vite', 'TypeScript', 'Architecture'],
    body: [
      'Temptation on day one is always to start building first. From experience, I resisted. Spent the whole first session on folder structure, Vite config, TypeScript setup, and the theme system. Wrote zero visible UI. Felt unproductive. Was actually the most productive day of the project.',
      'Went with feature-based folders (/features/cv, /features/github, etc) instead of the typical /components and /pages split. Every tutorial uses the flat structure but it falls apart once you have more than 10 components. This approach means everything related to GitHub integration lives in one folder.',
      'Chose Vite over CRA because CRA is basically dead (https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741). TypeScript in strict mode because loose TypeScript is pointless imo. Set up the dark theme with CSS variables so every component can reference --color-accent instead of hardcoding hex values.',
    ],
    lessonLearned: 'The first commit should be boring. Config files, folder structure, theme setup.',
  },
];
